package com.herobrinemod.herobrine.entities;

import com.herobrinemod.herobrine.HerobrineMod;
import net.minecraft.block.Blocks;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.Vec3d;

import static net.minecraft.registry.Registries.ENTITY_TYPE;

public class EntityTypeList {
    public static final EntityType<HerobrineWarriorEntity> HEROBRINE_WARRIOR = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "herobrine_warrior"), EntityType.Builder.create(HerobrineWarriorEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 1.8f).eyeHeight(1.62f).vehicleAttachment(PlayerEntity.VEHICLE_ATTACHMENT_POS).build());
    public static final EntityType<HerobrineSpyEntity> HEROBRINE_SPY = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "herobrine_spy"), EntityType.Builder.create(HerobrineSpyEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 1.8f).eyeHeight(1.62f).vehicleAttachment(PlayerEntity.VEHICLE_ATTACHMENT_POS).build());
    public static final EntityType<HerobrineMageEntity> HEROBRINE_MAGE = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "herobrine_mage"), EntityType.Builder.create(HerobrineMageEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 1.8f).eyeHeight(1.62f).vehicleAttachment(PlayerEntity.VEHICLE_ATTACHMENT_POS).build());
    public static final EntityType<FakeHerobrineMageEntity> FAKE_HEROBRINE_MAGE = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "fake_herobrine_mage"), EntityType.Builder.create(FakeHerobrineMageEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 1.8f).eyeHeight(1.62f).vehicleAttachment(PlayerEntity.VEHICLE_ATTACHMENT_POS).build());
    public static final EntityType<HerobrineBuilderEntity> HEROBRINE_BUILDER = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "herobrine_builder"), EntityType.Builder.create(HerobrineBuilderEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 1.8f).eyeHeight(1.62f).vehicleAttachment(PlayerEntity.VEHICLE_ATTACHMENT_POS).build());
    public static final EntityType<HerobrineStalkerEntity> HEROBRINE_STALKER = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "herobrine_stalker"), EntityType.Builder.create(HerobrineStalkerEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 1.8f).eyeHeight(1.62f).vehicleAttachment(PlayerEntity.VEHICLE_ATTACHMENT_POS).build());
    public static final EntityType<?> HOLY_WATER = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "holy_water"), EntityType.Builder.create((type, world) -> new HolyWaterEntity(world), SpawnGroup.MISC).dimensions(0.25f, 0.25f).build());
    public static final EntityType<?> UNHOLY_WATER = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "unholy_water"), EntityType.Builder.create((type, world) -> new UnholyWaterEntity(world), SpawnGroup.MISC).dimensions(0.25f, 0.25f).build());
    public static final EntityType<InfectedPigEntity> INFECTED_PIG = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_pig"), EntityType.Builder.create(InfectedPigEntity::new, SpawnGroup.MONSTER).dimensions(0.9f, 0.9f).eyeHeight(1.79f).passengerAttachments(0.86875f).build());
    public static final EntityType<InfectedCowEntity> INFECTED_COW = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_cow"), EntityType.Builder.create(InfectedCowEntity::new, SpawnGroup.MONSTER).dimensions(0.9f, 1.4f).eyeHeight(1.3f).passengerAttachments(1.36875f).build());
    public static final EntityType<InfectedVillagerEntity> INFECTED_VILLAGER = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_villager"), EntityType.Builder.create(InfectedVillagerEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 1.95f).eyeHeight(1.62f).build());
    public static final EntityType<InfectedChickenEntity> INFECTED_CHICKEN = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_chicken"), EntityType.Builder.create(InfectedChickenEntity::new, SpawnGroup.MONSTER).dimensions(0.4f, 0.7f).eyeHeight(0.644f).passengerAttachments(new Vec3d(0.0, 0.7, -0.1)).build());
    public static final EntityType<InfectedSheepEntity> INFECTED_SHEEP = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_sheep"), EntityType.Builder.create(InfectedSheepEntity::new, SpawnGroup.MONSTER).dimensions(0.9f, 1.3f).eyeHeight(1.235f).passengerAttachments(1.2375f).build());
    public static final EntityType<InfectedBatEntity> INFECTED_BAT = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_bat"), EntityType.Builder.create(InfectedBatEntity::new, SpawnGroup.MONSTER).dimensions(0.5f, 0.9f).eyeHeight(0.45f).build());
    public static final EntityType<InfectedWolfEntity> INFECTED_WOLF = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_wolf"), EntityType.Builder.create(InfectedWolfEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 0.85f).eyeHeight(0.68f).passengerAttachments(new Vec3d(0.0, 0.81875, -0.0625)).build());
    public static final EntityType<InfectedMooshroomEntity> INFECTED_MOOSHROOM = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_mooshroom"), EntityType.Builder.create(InfectedMooshroomEntity::new, SpawnGroup.MONSTER).dimensions(0.9f, 1.4f).eyeHeight(1.3f).passengerAttachments(1.36875f).build());
    public static final EntityType<InfectedDonkeyEntity> INFECTED_DONKEY = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_donkey"), EntityType.Builder.create(InfectedDonkeyEntity::new, SpawnGroup.MONSTER).dimensions(1.3964844f, 1.5f).eyeHeight(1.425f).passengerAttachments(1.1125f).build());
    public static final EntityType<InfectedHorseEntity> INFECTED_HORSE = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_horse"), EntityType.Builder.create(InfectedHorseEntity::new, SpawnGroup.MONSTER).dimensions(1.3964844f, 1.6f).eyeHeight(1.52f).passengerAttachments(1.44375f).build());
    public static final EntityType<?> INFECTED_LLAMA_SPIT = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_llama_spit"), EntityType.Builder.create((type, world) -> new InfectedLlamaSpitEntity(world), SpawnGroup.MISC).dimensions(0.25f, 0.25f).build());
    public static final EntityType<InfectedLlamaEntity> INFECTED_LLAMA = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_llama"), EntityType.Builder.create(InfectedLlamaEntity::new, SpawnGroup.MONSTER).dimensions(0.9f, 1.87f).eyeHeight(1.7765f).passengerAttachments(new Vec3d(0.0, 1.37, -0.3)).build());
    public static final EntityType<InfectedRabbitEntity> INFECTED_RABBIT = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_rabbit"), EntityType.Builder.create(InfectedRabbitEntity::new, SpawnGroup.MONSTER).dimensions(0.4f, 0.5f).build());
    public static final EntityType<SurvivorEntity> SURVIVOR = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "survivor"), EntityType.Builder.create( SurvivorEntity::new, SpawnGroup.MISC).dimensions(0.6f, 1.8f).eyeHeight(1.62f).vehicleAttachment(PlayerEntity.VEHICLE_ATTACHMENT_POS).build());
    public static final EntityType<InfectedAxolotlEntity> INFECTED_AXOLOTL = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_axolotl"), EntityType.Builder.create(InfectedAxolotlEntity::new, SpawnGroup.MONSTER).dimensions(0.75f, 0.42f).eyeHeight(0.2751f).build());
    public static final EntityType<InfectedCamelEntity> INFECTED_CAMEL = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_camel"), EntityType.Builder.create(InfectedCamelEntity::new, SpawnGroup.MONSTER).dimensions(1.7f, 2.375f).eyeHeight(2.275f).build());
    public static final EntityType<InfectedArmadilloEntity> INFECTED_ARMADILLO = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_armadillo"), EntityType.Builder.create(InfectedArmadilloEntity::new, SpawnGroup.MONSTER).dimensions(0.7f, 0.65f).eyeHeight(0.26f).build());
    public static final EntityType<InfectedOcelotEntity> INFECTED_OCELOT = Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_ocelot"), EntityType.Builder.create(InfectedOcelotEntity::new, SpawnGroup.MONSTER).dimensions(0.6f, 0.7f).eyeHeight(0.6375F).passengerAttachments(0.6375f).build());
    public static final EntityType<InfectedFoxEntity> INFECTED_FOX= Registry.register(ENTITY_TYPE, Identifier.of(HerobrineMod.MODID, "infected_fox"), EntityType.Builder.create(InfectedFoxEntity::new, SpawnGroup.MONSTER).dimensions(0.6F, 0.7F).eyeHeight(0.4F).passengerAttachments(new Vec3d(0.0, 0.6375, -0.25)).allowSpawningInside(Blocks.SWEET_BERRY_BUSH).build());
}